"""modified request

Revision ID: 118ca1401042
Revises: 7490ce3cd726
Create Date: 2021-04-01 01:13:21.499395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '118ca1401042'
down_revision = '7490ce3cd726'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('lat', sa.String(), nullable=True))
    op.add_column('request', sa.Column('long', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'long')
    op.drop_column('request', 'lat')
    # ### end Alembic commands ###
